"""initial_construction_schema

Revision ID: ac4e96eec649
Revises: 
Create Date: 2026-03-26 17:33:53.059280
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'ac4e96eec649'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_workspaces_slug')
    )
    op.create_index('ix_workspaces_is_active', 'workspaces', ['is_active'], unique=False)
    op.create_table('notification_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('notification_type', sa.String(length=40), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_jobs_status', 'notification_jobs', ['status'], unique=False)
    op.create_index('ix_notification_jobs_workspace_id', 'notification_jobs', ['workspace_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('project_code', sa.String(length=40), nullable=False),
    sa.Column('client_name', sa.String(length=160), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=False),
    sa.Column('sector', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('contract_value_usd', sa.Float(), nullable=False),
    sa.Column('target_margin_pct', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'project_code', name='uq_projects_workspace_code')
    )
    op.create_index('ix_projects_status', 'projects', ['status'], unique=False)
    op.create_index('ix_projects_workspace_id', 'projects', ['workspace_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_workspace_id', 'users', ['workspace_id'], unique=False)
    op.create_table('activity_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('actor_username', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_events_action', 'activity_events', ['action'], unique=False)
    op.create_index('ix_activity_events_created_at', 'activity_events', ['created_at'], unique=False)
    op.create_index('ix_activity_events_workspace_id', 'activity_events', ['workspace_id'], unique=False)
    op.create_table('permits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('jurisdiction', sa.String(length=160), nullable=False),
    sa.Column('package_name', sa.String(length=160), nullable=False),
    sa.Column('permit_number', sa.String(length=80), nullable=False),
    sa.Column('responsible_owner', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('submission_due_date', sa.Date(), nullable=True),
    sa.Column('submitted_at', sa.Date(), nullable=True),
    sa.Column('approved_at', sa.Date(), nullable=True),
    sa.Column('revision_requested_at', sa.Date(), nullable=True),
    sa.Column('inspection_due_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('inspection_status', sa.String(length=24), nullable=False),
    sa.Column('current_blocker', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_permits_project_id', 'permits', ['project_id'], unique=False)
    op.create_index('ix_permits_status', 'permits', ['status'], unique=False)
    op.create_index('ix_permits_workspace_id', 'permits', ['workspace_id'], unique=False)
    op.create_table('change_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('originating_permit_id', sa.String(length=36), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('affected_scope', sa.String(length=180), nullable=False),
    sa.Column('subcontractor_name', sa.String(length=140), nullable=False),
    sa.Column('owner_reference', sa.String(length=120), nullable=False),
    sa.Column('cost_impact_usd', sa.Float(), nullable=False),
    sa.Column('schedule_impact_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('risk_tags', sa.JSON(), nullable=False),
    sa.Column('required_action_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['originating_permit_id'], ['permits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('originating_permit_id', name='uq_change_events_originating_permit')
    )
    op.create_index('ix_change_events_project_id', 'change_events', ['project_id'], unique=False)
    op.create_index('ix_change_events_status', 'change_events', ['status'], unique=False)
    op.create_index('ix_change_events_workspace_id', 'change_events', ['workspace_id'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('permit_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('scheduled_for', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('inspector_name', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['permit_id'], ['permits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inspections_permit_id', 'inspections', ['permit_id'], unique=False)
    op.create_index('ix_inspections_workspace_id', 'inspections', ['workspace_id'], unique=False)
    op.create_table('permit_dependencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('permit_id', sa.String(length=36), nullable=False),
    sa.Column('depends_on_permit_id', sa.String(length=36), nullable=False),
    sa.Column('dependency_type', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_permit_id'], ['permits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permit_id'], ['permits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permit_id', 'depends_on_permit_id', name='uq_permit_dependencies_pair')
    )
    op.create_index('ix_permit_dependencies_workspace_id', 'permit_dependencies', ['workspace_id'], unique=False)
    op.create_table('change_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('change_event_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('number', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('schedule_impact_days', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.Date(), nullable=True),
    sa.Column('approved_at', sa.Date(), nullable=True),
    sa.Column('executed_at', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['change_event_id'], ['change_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'number', name='uq_change_orders_workspace_number')
    )
    op.create_index('ix_change_orders_change_event_id', 'change_orders', ['change_event_id'], unique=False)
    op.create_index('ix_change_orders_status', 'change_orders', ['status'], unique=False)
    op.create_index('ix_change_orders_workspace_id', 'change_orders', ['workspace_id'], unique=False)
    op.create_table('rfqs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('change_event_id', sa.String(length=36), nullable=False),
    sa.Column('subcontractor_name', sa.String(length=140), nullable=False),
    sa.Column('scope_summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('sent_at', sa.Date(), nullable=True),
    sa.Column('due_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['change_event_id'], ['change_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rfqs_change_event_id', 'rfqs', ['change_event_id'], unique=False)
    op.create_index('ix_rfqs_workspace_id', 'rfqs', ['workspace_id'], unique=False)
    op.create_table('approval_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('change_order_id', sa.String(length=36), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('role_required', sa.String(length=24), nullable=False),
    sa.Column('approver_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('decision_notes', sa.Text(), nullable=False),
    sa.Column('acted_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['change_order_id'], ['change_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approval_steps_change_order_id', 'approval_steps', ['change_order_id'], unique=False)
    op.create_index('ix_approval_steps_workspace_id', 'approval_steps', ['workspace_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('permit_id', sa.String(length=36), nullable=True),
    sa.Column('change_event_id', sa.String(length=36), nullable=True),
    sa.Column('change_order_id', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('extracted_fields', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['change_event_id'], ['change_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['change_order_id'], ['change_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permit_id'], ['permits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_project_id', 'documents', ['project_id'], unique=False)
    op.create_index('ix_documents_workspace_id', 'documents', ['workspace_id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('change_event_id', sa.String(length=36), nullable=False),
    sa.Column('rfq_id', sa.String(length=36), nullable=True),
    sa.Column('subcontractor_name', sa.String(length=140), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('quoted_at', sa.Date(), nullable=True),
    sa.Column('inclusions', sa.Text(), nullable=False),
    sa.Column('exclusions', sa.Text(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['change_event_id'], ['change_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quotes_change_event_id', 'quotes', ['change_event_id'], unique=False)
    op.create_index('ix_quotes_workspace_id', 'quotes', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quotes_workspace_id', table_name='quotes')
    op.drop_index('ix_quotes_change_event_id', table_name='quotes')
    op.drop_table('quotes')
    op.drop_index('ix_documents_workspace_id', table_name='documents')
    op.drop_index('ix_documents_project_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_approval_steps_workspace_id', table_name='approval_steps')
    op.drop_index('ix_approval_steps_change_order_id', table_name='approval_steps')
    op.drop_table('approval_steps')
    op.drop_index('ix_rfqs_workspace_id', table_name='rfqs')
    op.drop_index('ix_rfqs_change_event_id', table_name='rfqs')
    op.drop_table('rfqs')
    op.drop_index('ix_change_orders_workspace_id', table_name='change_orders')
    op.drop_index('ix_change_orders_status', table_name='change_orders')
    op.drop_index('ix_change_orders_change_event_id', table_name='change_orders')
    op.drop_table('change_orders')
    op.drop_index('ix_permit_dependencies_workspace_id', table_name='permit_dependencies')
    op.drop_table('permit_dependencies')
    op.drop_index('ix_inspections_workspace_id', table_name='inspections')
    op.drop_index('ix_inspections_permit_id', table_name='inspections')
    op.drop_table('inspections')
    op.drop_index('ix_change_events_workspace_id', table_name='change_events')
    op.drop_index('ix_change_events_status', table_name='change_events')
    op.drop_index('ix_change_events_project_id', table_name='change_events')
    op.drop_table('change_events')
    op.drop_index('ix_permits_workspace_id', table_name='permits')
    op.drop_index('ix_permits_status', table_name='permits')
    op.drop_index('ix_permits_project_id', table_name='permits')
    op.drop_table('permits')
    op.drop_index('ix_activity_events_workspace_id', table_name='activity_events')
    op.drop_index('ix_activity_events_created_at', table_name='activity_events')
    op.drop_index('ix_activity_events_action', table_name='activity_events')
    op.drop_table('activity_events')
    op.drop_index('ix_users_workspace_id', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_projects_workspace_id', table_name='projects')
    op.drop_index('ix_projects_status', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_notification_jobs_workspace_id', table_name='notification_jobs')
    op.drop_index('ix_notification_jobs_status', table_name='notification_jobs')
    op.drop_table('notification_jobs')
    op.drop_index('ix_workspaces_is_active', table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
